package edu.depaul.cdm.se452.dreamteam.windyhamhotel.contact;

import lombok.Data;

import java.io.Serializable;

import javax.persistence.*;

@Entity
@Data
@Table(name = "contact")
public class Contact implements Serializable
{
    //do not use @GeneratedValue(strategy = GenerationType.AUTO)
    @Id
    private String name;
    private String address;
    private String birth;
    private String gender;
    private String email;
    private String phone;

    public Contact( String name, String address,String birth, String gender, String email, String phone) 
    {
        this.name = name;
        this.address = address;
        this.birth = birth;
        this.gender = gender;
        this.email = email;
        this.phone = phone;
    }

    public Contact() 
    {

    }

    //Autogenerated getters/ setters not working
    public String getName()
    {
        return name;
    }
    public void setName(String name)
    {
        this.name = name;
    }

    public String getAddress()
    {
        return address;
    }
    public void setAddress(String address)
    {
        this.address = address;
    }

    public String getBirth()
    {
        return birth;
    }
    public void setBirth(String birth)
    {
        this.birth = birth;
    }

    public String getGender()
    {
        return gender;
    }
    public void setGender(String gender)
    {
        this.gender = gender;
    }

    public String getEmail()
    {
        return email;
    }
    public void setEmail(String email)
    {
        this.email = email;
    }

    public String getPhone()
    {
        return phone;
    }
    public void setPhone(String phone)
    {
        this.phone = phone;
    }
    
}
